addSbtPlugin("org.scalameta"         % "sbt-scalafmt"             % "2.4.6")
addSbtPlugin("com.typesafe.play"     % "sbt-twirl"                % "1.6.0-M6")
addSbtPlugin("io.spray"              % "sbt-revolver"             % "0.9.1")
addSbtPlugin("org.scala-js"          % "sbt-scalajs"              % "1.8.0")
addSbtPlugin("com.vmunier"           % "sbt-web-scalajs"          % "1.2.0")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"               % "7.4.0")
addSbtPlugin("org.portable-scala"    % "sbt-scalajs-crossproject" % "1.0.0")
